// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.ML;
using Microsoft.OpenApi;

// Configure app
var builder = WebApplication.CreateBuilder(args);
builder.Services.AddPredictionEnginePool<MLModelPrediction.ModelInput, MLModelPrediction.ModelOutput>()
    .FromFile("MLModelPrediction.mlnet");

// Add services (controllers, swagger, etc.)
builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Description = "Docs for my API", Version = "v1" });
});

var app = builder.Build();

app.UseSwagger();

if (app.Environment.IsDevelopment())
{
    app.UseSwagger();
    app.UseSwaggerUI(c =>
    {
        c.SwaggerEndpoint("/swagger/v1/swagger.json", "My API V1");
    });
}

app.UseHttpsRedirection();
app.UseAuthorization();

app.MapControllers();

// Define prediction route & handler
app.MapPost("/predict",
    async (PredictionEnginePool<MLModelPrediction.ModelInput, MLModelPrediction.ModelOutput> predictionEnginePool, MLModelPrediction.ModelInput input) =>
        await Task.FromResult(predictionEnginePool.Predict(input)));

// Ensure the root path returns content so browsers don't show a blank page
app.MapGet("/", () => Results.Content("<html><body><h1>API is running</h1><p>Try <a href=\"/swagger\">/swagger</a> or your API endpoints.</p></body></html>", "text/html"));

// Run app
app.Run();
